name: Update Profile README

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab
  schedule:
    - cron: '0 20 * * 0' # Runs at 20:00 UTC (8 PM) every Sunday

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: needs write permissions to commit to the repo
    steps:
      # Step 1: Check out the AmosDinh/AmosDinh repository
      - name: Check out main repo
        uses: actions/checkout@v4

      # Step 2: Check out the repo-stats repository into a separate directory
      - name: Check out stats repo
        uses: actions/checkout@v4
        with:
          repository: AmosDinh/repo-stats
          ref: github-repo-stats # The branch where your stats are
          path: ./repo-stats-data

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib

      # Step 5: Run the Python script to update the README
      - name: Run Python script
        run: python ./update_profile.py

      # Step 6: Commit and push the changes
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md clones_history.png
          # Commit only if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "docs: auto-update profile stats"
            git push
          else
            echo "No changes to commit."
          fi
